Show board based on database tables
pythoncanarias/web pull request #322
Opened 2020-11-27 10:30 UTC by euribates

Fixes issue #283 : Mostrar los cargos de la junta directiva según los datos existentes en la BD

Hay varias migraciones porque cree una nueva tabla `Role` para guardar los disntintos cargos que hay, y su ordenamiento. Las diferentes migraciones pasan del valor anterior, que era un simple codigo usando un `CHOICES` a referencias a la tabla `Role`

2020-11-27 14:34 UTC, jdevera requested changes
Creo que ahora que la página `about` necesita más datos en la base de datos, esta PR debería extender las acciones de `dev/management/commands/dbload.py` para incluir una junta directiva falsa que haga que la página de `about` funcione.

2020-11-27 14:34 UTC, jdevera commented on about/views.py
> +    organization = Organization.objects.get(
Confieso estar algo en desacuerdo con renombrar esto, mi base es esa idea de que este proyecto realmente no funciona como página genérica para asociaciones, sino que es específico de Python Canarias y en ocasiones sería más fácil de entender si aceptamos ese carácter específico. Aquí hay una tabla `organization` que guarda varias organizaciones pero con esta query estamos sacando un'ivocamente la correspondiente a Python Canarias. Yo lo dejaría así de explícito. Lo mismo para el cambio de variable en la plantilla un par de líneas más abajo y en el fichero de la plantilla en cuestión.

2020-11-27 14:34 UTC, jdevera commented on members/models.py
> +    po_box = models.CharField("Código postal", max_length=10, blank=True)
Raro, po_box es un apartado de correos, pero eso es una historia para otro día, creo.

2020-11-27 14:34 UTC, jdevera commented on members/models.py
> +    weight = models.IntegerField(default=100)
Los modelos de django no tiene algo para documentar campos? Ya me ha pasado que me he quedado pescando con algunos campos. Este es uno, por ejemplo.

2020-11-27 14:34 UTC, jdevera commented on members/templates/members/board.html
> +        de {{ orgnizacion.name }}
Typo en el nombre de la variable orgnizacion. Creo que tampoco coincide con la llamada que pinta esta plantilla.

2020-11-27 14:34 UTC, jdevera commented on members/urls.py
> +    path('board', views.board, name='board'),
La barra al final es relevante? veo que `join/` la tiene.

2020-11-29 11:55 UTC, euribates commented on about/views.py
> +    organization = Organization.objects.get(
Umm, sobre eso  no estoy totalmente de acuerdo. En mi opinion, deberiamos hacer el sistema lo más genérico _posible_. Con énfasis en lo de _posible_: Siempre deberiamos intentar que fuera genérico, y solo si encontramos algo que no se pueda hacer (o que fuera muy complicado) de forma genérica, entonces si hacer algo especifico de Python Canarias.

Para este caso de la estructura de la junta directiva, no veo ninguna razón para hacerlo especifico, ya que nuestra estructura organizativa no se diferencia en nada de la de otras organizaciones. Y con el modelo Role, se pueden definir nuevos cargos si hiciera falta. Podemos comentar estos enfoques el proximo martes.

Lo de incluir datos dummy es muy buena idea, me pongo a ello.

2020-11-29 11:56 UTC, euribates commented on members/models.py
> +    po_box = models.CharField("Código postal", max_length=10, blank=True)
Si, ami también me parecio raro, pero ya estaba cambiando muchas cosas en un solo issue. Admás, se usa con el mismo nombre y significado en otros modelos. Creare una issue para realizar este cambio en todos los modelos de una sola vez.

2020-11-29 12:01 UTC, euribates commented on members/models.py
> +    po_box = models.CharField("Código postal", max_length=10, blank=True)
Ya está creada la issue https://github.com/pythoncanarias/web/issues/325

2020-11-29 12:05 UTC, euribates commented on members/models.py
> +    weight = models.IntegerField(default=100)
Quiza se pueda usar el parámetro `help_text`.

En este caso el peso o `weight` es para ordenar el listado de los miembros de la junta. A veces se usa este concepto de peso porque además de especificar un ordenamiento tambien se especifica semáticamente un orden: Los más ligeros van arriba. Usar `order` daria problemas porque `ORDER` es una palabra reservada en SQL.

2020-11-29 16:20 UTC, euribates commented on members/models.py
> +    weight = models.IntegerField(default=100)
Añadia una explicacion con `help_text`

2020-11-29 16:22 UTC, euribates commented on members/urls.py
> +    path('board', views.board, name='board'),
Si que lo es, gracias.

Arreglado

2020-11-29 16:24 UTC, euribates commented on about/views.py
> +    organization = Organization.objects.get(
Ya estan incluidos los datos _dummy_ para la junta de gobierno. Hice además un par de cambios para hacer que `db_load` fuera idempotente. Échale un vistazo y me comentas.

2020-11-29 16:24 UTC, euribates commented on members/templates/members/board.html
> +        de {{ orgnizacion.name }}
Buen ojo, arreglado

2020-12-04 22:07 UTC, jdevera commented
Esto me pasa al ejecutar `dbload` después de arrancar todo y hacer `migrate`:

```python
root@77ca3056542e:/var/www/pycan# ./manage.py dbload
Adding own organization . ✓
Creating governing board
  - Creating president . Traceback (most recent call last):
  File "./manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/venv/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/venv/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/www/pycan/apps/dev/management/commands/dbload.py", line 281, in handle
    add_board()
  File "/var/www/pycan/apps/dev/management/commands/dbload.py", line 205, in add_board
    assign_role(president, clark_member)
  File "/var/www/pycan/apps/dev/management/commands/dbload.py", line 159, in assign_role
    membership = membership.objects.create(
AttributeError: 'NoneType' object has no attribute 'objects'```

2020-12-05 02:00 UTC, jdevera approved these changes

2020-12-08 19:12 UTC, sdelquin commented
He actualizado los cargos en django-admin pero no veo que se actualice en la web :cara_pensativa:

![image1](https://user-images.githubusercontent.com/1591599/101529948-25a7f880-3989-11eb-91aa-3d2b9dee3dac.png)
![image2](https://user-images.githubusercontent.com/1591599/101530060-51c37980-3989-11eb-8070-644ca5e6d58e.png)

2020-12-10 10:29 UTC, merged