docs: add branch names and semantic commit messages
pythoncanarias/web pull request #399
Opened 2021-10-06 18:07 UTC by CrisKrus

It has been added the standard for branch names and commit messages explained in #398

2021-10-06 18:22 UTC, jdevera requested changes
Gracias por la PR 🔥 !!!

Algunos comentarios, algunos de los cuales tienen relación con la conversación en la issue. Podemos hablarlo donde quieras.

2021-10-06 18:22 UTC, jdevera commented on CONTRIBUTING.md
> +A la hora de crear una rama para contribuir en este proyuecto hemos de seguir
```suggestion
A la hora de crear una rama para contribuir en este proyecto hemos de seguir
```

2021-10-06 18:22 UTC, jdevera commented on CONTRIBUTING.md
> +siguiente forma `git branch 389-add-blogs`. Es decir, ponemos como primera
Preferiría que indicásemos simplemente el nombre de la rama en lugar del comando, al fin y al cabo una forma común de crear una rama es con `git checkout -b`.

2021-10-06 18:22 UTC, jdevera commented on CONTRIBUTING.md
> +parte el número de la issue, luego el nombre en inglés.
Creo que no deberíamos enlazar tan directamente el título de la issue con el nombre de la rama. Yo aquí recomendaría algo como:
> y luego una corta descripción del objetivo de la rama separando cada plabara con guiones.

2021-10-06 18:22 UTC, jdevera commented on CONTRIBUTING.md
> +parte el número de la issue, luego el nombre en inglés.
Como ya comenté en la issue, no pondría lo del inglés, creo que no importa.

2021-10-06 18:22 UTC, jdevera commented on CONTRIBUTING.md
> +[semantic-commit-messages]:https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716
Lo dicho en la issue:

> Entiendo que es una herramienta útil, uso algo parecido en mis dotfiles, pero no estoy seguro de introducirlo como obligación, sobre todo cuando hasta ahora no lo hemos estado haciendo.

> Antes intentaría usarlo. Quizá la forma de usarlo es precisamente documentarlo, puedo verlo. Si así fuera, dejaría claro que este es el objetivo actual y podría una explicación completa de por qué y cuáles son nuestras etiquetas directamente en nuestra docu, no haciendo referencia a un gist de por ahí.

2021-10-06 18:22 UTC, jdevera commented on CONTRIBUTING.md
> +git branch <issue number>-<issue-name>
Y de hecho pondría `git --checkout -b` como comando principal, es lo que una quiere casi siempre.

2021-10-06 18:24 UTC, sdelquin requested changes

2021-10-06 18:24 UTC, sdelquin commented on CONTRIBUTING.md
> +A la hora de crear una rama para contribuir en este proyuecto hemos de seguir
"proyuecto" -> "proyecto"

2021-10-12 20:14 UTC, CrisKrus commented
> Hola @CrisKrus. @jdevera ahora no puede hacer las revisiones. ¿Hay algo que nos falte para mergear?

Por mi parte no falta nada, en la PR dice que hay cambios pendientes solicitados por @jdevera pero yo no veo que exista nada pendiente

2021-10-16 21:18 UTC, merged